." Manpage for dungeona
.TH DUNGEONA 1 "01 April 2026" "0.4.0" "Dungeona Manual"
.SH NAME
dungeona \- ANSI dungeon crawler and map editor
.SH SYNOPSIS
.B dungeona
.RI [ options ]
.SH DESCRIPTION
Dungeona is a small terminal-based dungeon crawler written in Python.
Run \fBdungeona\fR to start the game. Use the editor program \fBdungeon_editor\fR to edit maps.
.SH AUTHOR
Written by mtatton.
.SH LICENSE
MIT
